import type {
  Catalog,
  Period,
  Source,
  TimeSpan,
  TimelineEvent,
} from "../../core/types";
import { xinhaiCollection, xinhaiEntities, xinhaiEvents, xinhaiRelations, xinhaiSources } from './xinhai';

const source = (
  id: string,
  title: string,
  publisher: string,
  url: string,
  type = "机构资料",
): Source => ({ id, title, publisher, url, type, checkedAt: "2026-09-30" });
export const sources: Source[] = [
  source(
    "chronology",
    "中国历史纪年简表",
    "中央政府驻港联络办 · 转引中国政府网",
    "https://www.locpg.gov.cn/zggq/2014-01/04/c_125956418.htm",
  ),
  source(
    "columbia",
    "Timeline of Chinese Historical Periods",
    "哥伦比亚大学 Asia for Educators",
    "https://afe.easia.columbia.edu/timelines/china_timeline.htm",
    "教学参考",
  ),
  source(
    "tang-met",
    "Tang Dynasty (618–907)",
    "大都会艺术博物馆",
    "https://www.metmuseum.org/essays/tang-dynasty-618-906",
    "博物馆研究",
  ),
  source(
    "hulao",
    "荥阳这个地，真“虎”啊！",
    "荥阳市人民政府",
    "https://www.xingyang.gov.cn/bmdt/9869939.jhtml",
  ),
  source(
    "xuanwu",
    "626年7月2日 玄武门之变",
    "盐田档案与史志信息网",
    "https://www.yantian.gov.cn/ytdayszxxw/lsjt/content/post_11736532.html",
  ),
  source(
    "turk",
    "新疆的若干历史问题",
    "新疆维吾尔自治区自然资源厅",
    "https://zrzyt.xinjiang.gov.cn/xjgtzy/djgzxx/201910/d13245bdb7b84c1f9c003d3ed82f5b42.shtml",
  ),
  source(
    "buniantu",
    "阎立本步辇图卷",
    "故宫博物院",
    "https://www.dpm.org.cn/collection/paint/234620.html",
    "藏品说明",
  ),
  source(
    "wu-zhou",
    "三尊佛龛",
    "日本国立文化财机构 · 九州国立博物馆",
    "https://emuseum.nich.go.jp/detail?content_base_id=100012&content_part_id=0&content_pict_id=0&langId=zh&webView=",
    "藏品说明",
  ),
  source(
    "talas",
    "A Chronological Outline of Chinese History",
    "哥伦比亚大学 Asia for Educators",
    "https://afe.easia.columbia.edu/mongols/pop/menu/class_timeline.htm",
    "教学参考",
  ),
  source(
    "an-shi",
    "安史之乱：大唐盛衰记（公元755—763年）书目",
    "日本国立情报学研究所 CiNii",
    "https://cir.nii.ac.jp/crid/1971993809808096834",
    "研究书目",
  ),
  source(
    "tax",
    "两税法",
    "国家税务总局天津市税务局",
    "https://tianjin.chinatax.gov.cn/11248000000/8000/800001/80000105/20191025153613963.shtml",
  ),
  source(
    "diamond",
    "Buddhist texts: The Diamond Sutra",
    "英国国家图书馆 · 国际敦煌项目",
    "https://idp.bl.uk/discover/learning/buddhism-on-the-silk-roads/articles/buddhism-on-the-ground/buddhist-texts-the-diamond-sutra/",
    "藏品说明",
  ),
  source(
    "song-rivals",
    "Northern Rivals: Liao, Jin, Xi Xia, and the Mongols",
    "哥伦比亚大学 Asia for Educators",
    "https://afe.easia.columbia.edu/songdynasty-module/outside-rivals.html",
    "教学参考",
  ),
  source(
    "caishi",
    "采石之战",
    "上贡井 · 地方融媒体",
    "https://m.gjzc.cn/content/61b477c49e766",
    "历史回顾",
  ),
  ...xinhaiSources,
];
const duration = (
  start: number,
  end: number,
  approximate = false,
): TimeSpan => ({
  kind: "duration",
  start: { year: start, ...(approximate ? { approximate: true } : {}) },
  end: { year: end },
});
const period = (
  id: string,
  title: string,
  start: number,
  end: number,
  summary: string,
  extra: Partial<Period> = {},
): Period => ({
  id,
  title,
  time: duration(start, end),
  summary,
  entityIds: [id],
  sourceIds: ["chronology"],
  coverage: "outline",
  ...extra,
});
export const periods: Period[] = [
  period("xia", "夏", -2070, -1600, "早期王朝的传统纪年。", {
    time: {
      kind: "duration",
      start: { year: -2070, approximate: true },
      end: { year: -1600, approximate: true },
    },
    note: "年代采用参考简表的近似纪年；起源与考古对应关系仍有讨论。",
  }),
  period(
    "shang",
    "商",
    -1600,
    -1046,
    "从早期王朝进入有文字材料可参照的历史。",
    { time: duration(-1600, -1046, true) },
  ),
  period(
    "zhou",
    "周与列国",
    -1046,
    -221,
    "展开西周、东周与春秋战国的阅读层级。",
    {
      note: "这是阅读分期，包含战国末期；周王室终结于前256年，不能将前221年当作周王室终年。",
    },
  ),
  period("western-zhou", "西周", -1046, -771, "周的早期阶段。", {
    parentId: "zhou",
  }),
  period("eastern-zhou", "东周", -770, -256, "东周王室存续时期。", {
    parentId: "zhou",
  }),
  period("spring-autumn", "春秋", -770, -476, "列国历史的一个分期。", {
    parentId: "zhou",
    note: "春秋与战国的分界存在不同口径；此处采用前476／前475年的分期。",
  }),
  period("warring-states", "战国", -475, -221, "列国竞争延续至秦统一。", {
    parentId: "zhou",
  }),
  period("qin", "秦", -221, -206, "以秦王朝为线索的历史。", {
    sourceIds: ["columbia"],
    note: "终年采用前206年；不同纪年表亦有前207年的记法。",
  }),
  period(
    "han",
    "汉",
    -202,
    220,
    "展开西汉与东汉；其间的政权变化不等于汉连续统治。",
    { note: "起点按前202年称帝口径，部分资料以汉王建国的前206年为起点。" },
  ),
  period("western-han", "西汉", -202, 8, "汉的前期。", {
    parentId: "han",
    note: "这里按参考简表记至公元8年；有资料按新朝建立记至9年。",
  }),
  period("eastern-han", "东汉", 25, 220, "汉的后期。", { parentId: "han" }),
  period(
    "division",
    "三国两晋南北朝",
    220,
    589,
    "多政权并存的阅读分组，展开后使用同一时间刻度。",
    { entityIds: [], sourceIds: ["chronology", "columbia"] },
  ),
  period("wei", "曹魏", 220, 265, "三国中的一个政权。", {
    parentId: "division",
  }),
  period("shu", "蜀汉", 221, 263, "三国中的一个政权。", {
    parentId: "division",
  }),
  period("wu", "孙吴", 222, 280, "三国中的一个政权。", {
    parentId: "division",
    note: "起点采用称吴王的222年口径。",
  }),
  period("western-jin", "西晋", 265, 316, "两晋的前期。", {
    parentId: "division",
  }),
  period("eastern-jin", "东晋", 317, 420, "两晋的后期。", {
    parentId: "division",
  }),
  period("sixteen-kingdoms", "十六国", 304, 439, "多个政权的时期分组。", {
    parentId: "division",
    entityIds: [],
  }),
  period("northern-dynasties", "北朝", 386, 581, "北方诸朝的时期分组。", {
    parentId: "division",
    entityIds: [],
  }),
  period("southern-dynasties", "南朝", 420, 589, "南方诸朝的时期分组。", {
    parentId: "division",
    entityIds: [],
  }),
  period("sui", "隋", 581, 618, "隋朝与南北朝末期在时间上交叠。"),
  period("tang", "唐", 618, 907, "从王朝建立、对外往来到战争与制度变化。", {
    sourceIds: ["tang-met"],
    coverage: "selected",
    note: "总览使用618—907年的唐代分期，内含武周；不表示李唐统治从未中断。",
  }),
  period(
    "wu-zhou",
    "武周",
    690,
    705,
    "武则天称帝时期，作为唐代阅读分期内的独立政权列出。",
    { parentId: "tang", sourceIds: ["wu-zhou"], coverage: "selected" },
  ),
  period(
    "five-dynasties",
    "五代十国",
    907,
    979,
    "多个政权的时期分组，与宋初存在交叠。",
    { entityIds: [] },
  ),
  period(
    "song-era",
    "宋辽夏金",
    916,
    1279,
    "展开并行的政权；分组不表示各政权互相隶属。",
    {
      entityIds: [],
      sourceIds: ["chronology", "columbia", "song-rivals"],
      coverage: "selected",
    },
  ),
  period("song", "宋", 960, 1279, "北宋与南宋的整体阅读入口。", {
    parentId: "song-era",
    sourceIds: ["columbia"],
    coverage: "selected",
    note: "终年采用1279年；1276年临安陷落是另一常见分期节点。",
  }),
  period(
    "northern-song",
    "北宋",
    960,
    1127,
    "宋的前期，与辽、金等政权处于同一时间背景。",
    { parentId: "song", sourceIds: ["columbia"], coverage: "selected" },
  ),
  period("southern-song", "南宋", 1127, 1279, "宋的后期。", {
    parentId: "song",
    sourceIds: ["columbia"],
    coverage: "selected",
  }),
  period("liao", "辽", 916, 1125, "与宋等政权并存。", {
    parentId: "song-era",
    note: "采用916年建国口径；部分教学资料将起点前推至907年。",
    coverage: "selected",
  }),
  period("western-xia", "西夏", 1038, 1227, "宋辽夏金时期的一个政权。", {
    parentId: "song-era",
  }),
  period("jin", "金", 1115, 1234, "与宋等政权并存。", {
    parentId: "song-era",
    coverage: "selected",
  }),
  period(
    "yuan",
    "元",
    1271,
    1368,
    "按1271年定国号口径起算，保留与南宋的交叠。",
    { note: "1279年是南宋结束的节点，不等同于元朝定国号之年。" },
  ),
  period("ming", "明", 1368, 1644, "以明王朝为线索的历史。", {
    note: "总览采用明朝通常分期；南明等后续政权尚未展开。",
  }),
  period("qing", "清", 1644, 1912, "此处按入关至清帝退位的阅读分期展示。", {
    sourceIds: ["columbia"],
    note: "1644年是入关口径；1636年改国号等更早阶段待补充。",
  }),
  period('late-qing-republic', '清末民初：辛亥革命与共和建政', 1911, 1912,
    '跨政权的专题阅读分期，包含清廷存续、地方起义、南京建政与总统交接。', {
      entityIds: [], coverage: 'selected', sourceIds: ['xinhai-chronology', 'xinhai-frus-overview'],
      note: '阅读分组，不是一个政权；不把共和事件归为清廷内部事件。1912 年两个临时政府的协调与交接分阶段进行。',
    }),
  period('early-republic', '民国初年：1912 建政与交接', 1912, 1912,
    '本版仅展开 1912 年共和建政、总统交接和约法，不代表民国整体存续范围。', {
      time: { kind: 'duration', start: { year: 1912, month: 1, day: 1 }, end: { year: 1912, month: 12, day: 31 } },
      entityIds: [], coverage: 'selected', sourceIds: ['xinhai-exhibition', 'xinhai-frus-overview'],
      note: '与清的末期在 1912 年并行；全年阅读范围不表示南京政府一直存续到年底。',
    }),
];

const event = (
  id: string,
  title: string,
  year: number,
  category: string,
  periodIds: string[],
  summary: string,
  sourceIds: string[],
  extra: Partial<TimelineEvent> = {},
): TimelineEvent => ({
  id,
  title,
  time: { kind: "point", start: { year } },
  category,
  periodIds,
  entityIds: periodIds.filter(
    (id) => periods.find((p) => p.id === id)?.entityIds.length,
  ),
  summary,
  significance: "将这一节点与前后事件放在一起，可以观察历史变化的节奏。",
  sourceIds,
  tags: [],
  milestone: true,
  ...extra,
});
export const events: TimelineEvent[] = [
  event(
    "qin-unification",
    "秦统一",
    -221,
    "politics",
    ["qin", "warring-states"],
    "秦建立统一王朝，成为总览中先秦与帝国时期之间的节点。",
    ["talas"],
    {
      significance:
        "政治组织进入新的阶段；后续制度的形成仍需结合具体史料理解。",
    },
  ),
  event(
    "tang-founded",
    "唐朝建立",
    618,
    "politics",
    ["tang"],
    "唐朝的起始节点。",
    ["tang-met"],
    { significance: "从这里进入唐代的制度、战争与文化发展。" },
  ),
  event(
    "hulao",
    "虎牢之战",
    621,
    "battle",
    ["tang"],
    "李世民在虎牢一带击败窦建德军队。",
    ["hulao"],
    {
      significance: "这是唐初统一进程中的重要战役。",
      details: [
        { label: "参战方", text: "唐军、窦建德军" },
        { label: "地点", text: "虎牢关一带，今河南荥阳" },
      ],
      note: "首版保留年份；不采用回顾文章中的兵力数字作为确定事实。",
    },
  ),
  event(
    "xuanwu",
    "玄武门之变",
    626,
    "politics",
    ["tang"],
    "李世民发动宫廷政变，随后取得皇位。",
    ["xuanwu"],
    {
      significance: "唐初皇位继承格局发生改变。",
      note: "此处仅按年展示，不混用传统历法与现代日期换算。",
    },
  ),
  event(
    "eastern-turks",
    "唐击败东突厥",
    630,
    "battle",
    ["tang"],
    "唐军击败东突厥汗国。",
    ["turk"],
    {
      significance: "这是唐初北方军事关系中的重要节点。",
      details: [{ label: "参战方", text: "唐、东突厥" }],
    },
  ),
  event(
    "wencheng",
    "文成公主入藏",
    641,
    "diplomacy",
    ["tang"],
    "文成公主与松赞干布联姻。",
    ["buniantu"],
    {
      significance: "提供理解唐与吐蕃交往的一条线索。",
      details: [{ label: "关联对象", text: "唐、吐蕃、文成公主、松赞干布" }],
    },
  ),
  event(
    "wu-emperor",
    "武则天称帝",
    690,
    "politics",
    ["tang", "wu-zhou"],
    "武则天进入称帝时期。",
    ["wu-zhou"],
    { significance: "唐代整体分期内部的政权变化应单独呈现。" },
  ),
  event(
    "xuanzong",
    "唐玄宗即位",
    712,
    "politics",
    ["tang"],
    "唐玄宗开始其统治。",
    ["tang-met"],
    {
      milestone: false,
      significance: "为观察八世纪唐代政治与文化变化提供一个时间参照。",
    },
  ),
  event(
    "talas",
    "怛罗斯之战",
    751,
    "battle",
    ["tang"],
    "唐军在中亚怛罗斯战役中败于阿拉伯军队。",
    ["talas"],
    {
      significance: "展示唐代军事活动与中亚历史的交汇。",
      note: "不将战役结果直接等同于丝绸之路交流的终结。",
    },
  ),
  event(
    "an-shi",
    "安史之乱",
    755,
    "war",
    ["tang"],
    "755—763年的持续战争削弱了唐廷权力。",
    ["an-shi", "tang-met"],
    {
      time: duration(755, 763),
      significance: "是理解唐代中后期政治变化的重要背景。",
      note: "这是持续战争，单列于“战争与动乱”，不当作单场战役。书目用于核对起止年份；影响概述参考博物馆研究。",
    },
  ),
  event(
    "two-tax",
    "推行两税法",
    780,
    "institution",
    ["tang"],
    "唐德宗时期，杨炎主持制定两税法。",
    ["tax"],
    {
      significance:
        "征税方式向土地、财产等依据调整，是唐代财政制度的变化节点。",
    },
  ),
  event(
    "diamond-sutra",
    "有纪年的《金刚经》刻本",
    868,
    "culture",
    ["tang"],
    "现存这一完整雕版印刷卷子具有868年的题记。",
    ["diamond"],
    {
      significance: "为研究印刷与佛教文本传播提供实物证据。",
      note: "这是存世有纪年印本的证据，不是印刷术发明年份。",
    },
  ),
  event(
    "tang-ended",
    "唐朝结束",
    907,
    "politics",
    ["tang", "five-dynasties"],
    "总览从唐代转入五代十国时期。",
    ["chronology", "tang-met"],
    { significance: "朝代边界与区域政权演变需要分层阅读。" },
  ),
  event(
    "song-founded",
    "宋朝建立",
    960,
    "politics",
    ["song", "northern-song"],
    "宋朝的起始节点。",
    ["columbia"],
    { significance: "宋的时间范围与辽、西夏、金等政权交叠。" },
  ),
  event(
    "chanyuan",
    "澶渊之盟",
    1005,
    "diplomacy",
    ["song", "northern-song", "liao"],
    "宋与辽达成和约，宋向辽支付岁币。",
    ["song-rivals"],
    {
      significance: "同一事件同时关联宋与辽，两条时间线引用同一记录。",
      note: "年份按公元1005年记；传统纪年中的年末与公历年初可能造成不同标注。",
    },
  ),
  event(
    "liao-ended",
    "辽结束",
    1125,
    "politics",
    ["liao", "jin"],
    "金击败辽，区域政权格局发生变化。",
    ["song-rivals"],
    { significance: "政权的先后关系与并存关系需要放在同一刻度下观察。" },
  ),
  event(
    "southern-song-start",
    "进入南宋时期",
    1127,
    "politics",
    ["song", "northern-song", "southern-song", "jin"],
    "宋的历史进入南宋阶段。",
    ["columbia", "song-rivals"],
    { significance: "同一年可以是一个分期的结束，也是另一个分期的开始。" },
  ),
  event(
    "caishi",
    "采石之战",
    1161,
    "battle",
    ["song", "southern-song", "jin"],
    "虞允文组织宋军，在采石阻止金军渡江。",
    ["caishi"],
    {
      significance: "这场宋金战役可以从南宋或金的时间线进入。",
      details: [
        { label: "参战方", text: "南宋、金" },
        { label: "地点", text: "采石，今安徽马鞍山一带" },
      ],
      note: "采用年份精度，不在首版给出争议兵力或伤亡统计。",
    },
  ),
  event(
    "yuan-named",
    "元朝定国号",
    1271,
    "politics",
    ["yuan"],
    "元朝分期按定国号之年起算。",
    ["chronology", "talas"],
    { significance: "与南宋结束的1279年分开记录。" },
  ),
  event(
    "song-ended",
    "南宋结束",
    1279,
    "politics",
    ["song", "southern-song", "yuan"],
    "南宋结束，元的统治进入新的阶段。",
    ["columbia", "song-rivals"],
    { significance: "王朝建立与完成征服不是同一个日期。" },
  ),
  ...xinhaiEvents,
];
export const chinaHistory: Catalog = {
  topic: {
    periodLabel: "朝代与时期",
    periodSegment: "dynasties",
    shortcuts: [
      { title: "朝代总览", path: "/china-history/" },
      { title: "从唐朝开始", path: "/china-history/dynasties/tang/" },
      { title: "看宋辽夏金并存", path: "/china-history/dynasties/song-era/" },
      { title: "跨朝代战役", path: "/china-history/themes/battles/" },
      { title: "辛亥革命 1911—1912", path: xinhaiCollection.path },
    ],
    id: "china-history",
    title: "中国历史",
    path: "/china-history/",
    description: "沿着朝代读历史，也沿着一场战役走进一个时代。",
    coverage:
      "夏至民初的时期骨架；唐代、宋辽夏金与辛亥革命 1911—1912 精选事件。其余时期以骨架为主，事件仍在补充。",
    categories: [
      { id: "politics", title: "政治与更替" },
      { id: "battle", title: "重大战役" },
      { id: "war", title: "战争与动乱" },
      { id: "institution", title: "制度与经济" },
      { id: "culture", title: "文化与技术" },
      { id: "diplomacy", title: "交流与外交" },
    ],
  },
  periods,
  events,
  sources,
  collections: [xinhaiCollection],
  relations: xinhaiRelations,
  entities: [...periods
    .filter((p) => p.entityIds.length)
    .map((p) => ({
      id: p.id,
      name: p.title,
      type: "历史对象",
      sourceIds: p.sourceIds,
    })), ...xinhaiEntities],
};
