import type { Source } from './types';
import { globalSources } from './global';
import { releaseSources, releaseResearchDate } from './releases';
import { instructionSources, instructionSourceReviews } from './instruction-following';
const source = (id: string, title: string, publisher: string, url: string, type: Source['type'] = '原始论文'): Source => ({ id, title, publisher, url, type, language: 'English', checkedAt: '2026-09-29' });
const baseSources: Source[] = [
  ...globalSources,
  ...releaseSources,
  source('mcp', 'Introducing the Model Context Protocol', 'Anthropic', 'https://www.anthropic.com/news/model-context-protocol', '官方公告'),
  source('context-engineering', 'Effective context engineering for AI agents', 'Anthropic', 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', '工程文章'),
  source('tool-engineering', 'Writing effective tools for AI agents', 'Anthropic', 'https://www.anthropic.com/engineering/writing-tools-for-agents', '工程文章'),
  source('multi-agent', 'How we built our multi-agent research system', 'Anthropic', 'https://www.anthropic.com/engineering/multi-agent-research-system', '工程文章'),
  source('managed-agents', 'Scaling Managed Agents', 'Anthropic', 'https://www.anthropic.com/engineering/managed-agents', '工程文章'),
  ...[
    ['word2vec', 'Efficient Estimation of Word Representations in Vector Space', '1301.3781'],
    ['vae', 'Auto-Encoding Variational Bayes', '1312.6114'],
    ['gan', 'Generative Adversarial Networks', '1406.2661'],
    ['resnet', 'Deep Residual Learning for Image Recognition', '1512.03385'],
    ['bert', 'BERT: Pre-training of Deep Bidirectional Transformers', '1810.04805'],
    ['gpt3', 'Language Models are Few-Shot Learners', '2005.14165'],
    ['cot', 'Chain-of-Thought Prompting Elicits Reasoning', '2201.11903'],
    ['instructgpt', 'Training language models to follow instructions with human feedback', '2203.02155'],
    ['dpo', 'Direct Preference Optimization', '2305.18290'],
    ['lora', 'LoRA: Low-Rank Adaptation of Large Language Models', '2106.09685'],
    ['ddpm', 'Denoising Diffusion Probabilistic Models', '2006.11239'],
    ['rag', 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks', '2005.11401'],
    ['toolformer', 'Toolformer: Language Models Can Teach Themselves to Use Tools', '2302.04761'],
    ['v2', 'DeepSeek-V2 Technical Report', '2405.04434'],
    ['v3', 'DeepSeek-V3 Technical Report', '2412.19437'],
  ].map(([id, title, arxiv]) => source(id, title, 'arXiv', `https://arxiv.org/abs/${arxiv}`)),
  source('claude2', 'Claude 2', 'Anthropic', 'https://www.anthropic.com/news/claude-2', '官方公告'),
  source('claude21', 'Introducing Claude 2.1', 'Anthropic', 'https://www.anthropic.com/news/claude-2-1', '官方公告'),
  source('claude3', 'Introducing the next generation of Claude', 'Anthropic', 'https://www.anthropic.com/news/claude-3-family', '官方公告'),
  source('sonnet35', 'Introducing Claude 3.5 Sonnet', 'Anthropic', 'https://www.anthropic.com/news/claude-3-5-sonnet', '官方公告'),
  source('computer-use', 'Introducing computer use and upgraded Claude 3.5 models', 'Anthropic', 'https://www.anthropic.com/news/3-5-models-and-computer-use', '官方公告'),
  source('sonnet45', 'Introducing Claude Sonnet 4.5', 'Anthropic', 'https://www.anthropic.com/news/claude-sonnet-4-5', '官方公告'),
  source('sonnet46', 'Introducing Sonnet 4.6', 'Anthropic', 'https://www.anthropic.com/news/claude-sonnet-4-6', '官方公告'),
  source('sonnet5', 'Introducing Claude Sonnet 5', 'Anthropic', 'https://www.anthropic.com/news/claude-sonnet-5', '官方公告'),
  source('r1-0528', 'DeepSeek-R1-0528 Release', 'DeepSeek', 'https://api-docs.deepseek.com/news/news250528/', '官方公告'),
  { ...source('api-changelog', 'OpenAI API changelog', 'OpenAI', 'https://developers.openai.com/api/docs/changelog', '官方公告'), checkedAt: releaseResearchDate },
  source('codex-changelog', 'ChatGPT & Codex changelog', 'OpenAI', 'https://learn.chatgpt.com/docs/changelog', '官方公告'),
  source('mcculloch', 'A logical calculus of the ideas immanent in nervous activity', 'Springer', 'https://doi.org/10.1007/BF02478259'),
  source('turing', 'Computing Machinery and Intelligence', 'Mind / Oxford', 'https://academic.oup.com/mind/article/LIX/236/433/986238'),
  source('dartmouth', 'A Proposal for the Dartmouth Summer Research Project on Artificial Intelligence', 'John McCarthy et al.', 'https://www-formal.stanford.edu/jmc/history/dartmouth/dartmouth.html'),
  source('dartmouth-history', 'Our Story', 'Dartmouth', 'https://ai.dartmouth.edu/our-story', '机构回顾'),
  source('chm', 'AI & Robotics · Timeline of Computer History', 'Computer History Museum', 'https://www.computerhistory.org/timeline/ai-robotics/', '机构回顾'),
  source('backprop', 'Learning representations by back-propagating errors', 'Nature', 'https://www.nature.com/articles/323533a0'),
  source('deep-blue', 'Deep Blue', 'IBM', 'https://www.ibm.com/history/deep-blue', '机构回顾'),
  source('watson', 'Watson, Jeopardy! champion', 'IBM', 'https://www.ibm.com/history/watson-jeopardy', '机构回顾'),
  source('alexnet', 'ImageNet Classification with Deep Convolutional Neural Networks', 'NeurIPS', 'https://papers.nips.cc/paper_files/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html'),
  source('alphago', 'AlphaGo', 'Google DeepMind', 'https://deepmind.google/research/alphago/', '机构回顾'),
  source('transformer', 'Attention Is All You Need', 'arXiv', 'https://arxiv.org/abs/1706.03762'),
  source('chatgpt', 'Introducing ChatGPT', 'OpenAI', 'https://openai.com/index/chatgpt/', '官方公告'),
  source('react', 'ReAct: Synergizing Reasoning and Acting in Language Models', 'arXiv', 'https://arxiv.org/abs/2210.03629'),
  source('agents', 'Building effective agents', 'Anthropic', 'https://www.anthropic.com/engineering/building-effective-agents', '工程文章'),
  source('skills', 'Equipping agents for the real world with Agent Skills', 'Anthropic', 'https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills', '工程文章'),
  source('harness', 'Effective harnesses for long-running agents', 'Anthropic', 'https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents', '工程文章'),
  source('harness-2026', 'Harness design for long-running application development', 'Anthropic', 'https://www.anthropic.com/engineering/harness-design-long-running-apps', '工程文章'),
  source('sonnet37', 'Claude 3.7 Sonnet and Claude Code', 'Anthropic', 'https://www.anthropic.com/news/claude-3-7-sonnet', '官方公告'),
  source('claude4', 'Introducing Claude 4', 'Anthropic', 'https://www.anthropic.com/news/claude-4', '官方公告'),
  source('r1', 'DeepSeek-R1 Release', 'DeepSeek', 'https://api-docs.deepseek.com/news/news250120/', '官方公告'),
  source('manus16', 'Introducing Manus 1.6', 'Manus', 'https://manus.im/en/blog/manus-max-release', '官方公告'),
  { ...source('manus2', 'Manus 2.0 正式登场', 'Manus', 'https://manus.im/zh-cn/blog/introducing-manus-2-0', '官方公告'), language: '简体中文' },
  source('grokbot', 'Meet Grok Bot', 'xAI', 'https://x.ai/bot', '官方文档'),
  source('grok-releases', 'Release Notes', 'xAI', 'https://docs.x.ai/developers/release-notes', '官方公告'),
  source('muse', 'How We Designed Muse', 'Muse / Meta', 'https://introducing.muse.ai/', '工程文章'),
  source('cue', 'Your personal agents, on Cue', 'Cue / Manus', 'https://cue.im/', '官方文档'),
];
export const sources: Source[] = [...baseSources.map(s => ({ ...s, ...instructionSourceReviews[s.id] })), ...instructionSources];
export const sourceMap = Object.fromEntries(sources.map(s => [s.id, s]));
